services:
  # The Web Application Service
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=cars_db
      - DB_USER=myuser
      - DB_PASS=mypassword
      - DB_PASS=mypassword
    networks:
      default:
        aliases:
          - web-service.car-app.svc.cluster.local
    depends_on:
      - db

  # The Database Service
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cars_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      # This seeds the DB with a script on first start
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      # This persists the data so it survives container restarts
      - postgres_data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - db.car-app.svc.cluster.local

  # DB Exporter
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.18.1
    networks:
      default:
        aliases:
          - postgres-exporter-service.monitoring.svc.cluster.local
    environment:
      DATA_SOURCE_NAME: "postgresql://myuser:mypassword@db:5432/cars_db?sslmode=disable"
    depends_on:
      - db

  # Prometheus Dtasource
  prometheus:
    image: prom/prometheus:v3.5.1
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      default:
        aliases:
          - prometheus-service.monitoring.svc.cluster.local

  # Monitoring Visuallization Tool
  grafana:
    image: grafana/grafana:12.3-ubuntu
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

# Define the volume for persistence
volumes:
  postgres_data:
  grafana_data:
