apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: car-app
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: "cars_db"
        - name: POSTGRES_USER
          value: "myuser"
        - name: POSTGRES_PASSWORD
          value: "mypassword"
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: init-script
        configMap:
          name: db-init-config
      - name: db-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: car-app
spec:
  selector:
    app: db
  ports:
    - port: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: car-app
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
